[project]
name = "taming-the-ito-lyon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "diffrax>=0.7.0",
    "equinox>=0.13.2",
    "jax[cuda]>=0.8.0",
    "optax>=0.2.6",
    "numpy>=2.0.0",
    "pydantic>=2.12.3",
    "tqdm>=4.67.1",
    "quicksig @ git+https://github.com/luke-a-thompson/QuickSig.git@master",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["taming_the_ito_lyon"]

[tool.hatch.metadata]
allow-direct-references = true
