[experiment_config]
model_type = "ncde"
dataset_name = "rough_bergomi"

# Optimizer
optimizer = "adamw"
learning_rate = 3e-4
weight_decay = 0.000001
max_grad_norm = 1.0

# Training
loss = "sigker"
seed = 1
batch_size = 1024
epochs = 100

# Training mode
training_mode = "unconditional"
# Unconditional generation samples a Brownian motion with this many channels.

manifold = "euclidean"
hidden_manifold = "euclidean"
evolving_out = true

[solver_config]
stepsize_controller = "pid"
rtol = 1e-3
atol = 1e-3
dtmin = 1e-4

[ncde_config]

# NCDE model parameters
cde_state_dim = 32
init_hidden_dim = 32
vf_hidden_dim = 32
initial_cond_mlp_depth = 2
vf_mlp_depth = 3
out_size = 1
control_interpolation = "hermite_cubic" # "hermite_cubic" | "linear"
