[experiment_config]
model_type = "nrde"
dataset_name = "sg_so3_simulation"

# Extrapolation settings
extrapolation_scheme = "hermite"
n_recon = 12

# Optimizer
optimizer = "adamw"
learning_rate = 3e-4
weight_decay = 0.000001
max_grad_norm = 1.0

# Training
loss = "frobenius"
seed = 1
batch_size = 1024
epochs = 15
early_stopping_patience = 5

# Training mode
training_mode = "conditional"
# Unconditional generation samples a Brownian motion with this many channels.

manifold = "euclidean"
hidden_manifold = "euclidean"
evolving_out = true

[solver_config]
stepsize_controller = "pid"
rtol = 1e-3
atol = 1e-4
dtmin = 1e-4

[nrde_config]

# NRDE model parameters
cde_state_dim = 16
init_hidden_dim = 32
vf_hidden_dim = 32
initial_cond_mlp_depth = 2
vf_mlp_depth = 3
out_size = 1

# Log-signature configuration
signature_depth = 2
signature_window_size = 10
