[experiment_config]
model_type = "log_ncde"
dataset_name = "ou_process"

# Optimizer
optimizer = "adam"
learning_rate = 0.001
weight_decay = 0.000001
max_grad_norm = 1.0

# Training
loss = "mse"
seed = 1
batch_size = 96
epochs = 200

# Training mode
training_mode = "conditional"
# To run unconditional generation, switch training_mode and set:
# unconditional_driver_kind = "bm"   # "bm" | "fbm" | "rl"
# unconditional_driver_dim = 1       # number of non-time channels
# unconditional_hurst = 0.1          # used for "fbm"/"rl"

[log_ncde_config]

# Log-NCDE model parameters
cde_state_dim = 16         # Jacobian burden, quadratic in this
vf_hidden_dim = 32
initial_cond_mlp_depth = 2
vf_mlp_depth = 3
out_size = 1

# Log-signature configuration
signature_depth = 2
signature_window_size = 16
