[experiment_config]
model_type = "mnrde"
dataset_name = "ou_process"

# Extrapolation settings
use_extrapolation = false
extrapolation_scheme = "sg"
n_recon = 12

# Optimizer
optimizer = "adam"
learning_rate = 0.001
weight_decay = 0.000001
max_grad_norm = 1.0

# Training
loss = "mse"
seed = 1
batch_size = 64
epochs = 200

[mnrde_config]

# M-NRDE model parameters
cde_state_dim = 16
vf_hidden_dim = 32
initial_cond_mlp_depth = 2
vf_mlp_depth = 3
out_size = 1

# Log-signature configuration
signature_depth = 2
signature_window_size = 16

hopf_algebra = "shuffle"
