[experiment_config]
model_type = "ncde"
dataset_name = "ou_process"
optimizer = "adam"
learning_rate = 0.001
weight_decay = 0.000001
seed = 1
batch_size = 128
epochs = 200

[ncde_config]

# NCDE model parameters
cde_state_dim = 64
vf_hidden_dim = 64
initial_cond_mlp_depth = 2
vf_mlp_depth = 3
out_size = 1

# Solver tolerances
rtol = 0.001
atol = 0.000001
dtmin = 1e-6
