[experiment_config]
dataset_name = "ou_process"
optimizer = "adam"
learning_rate = 0.001
weight_decay = 0.000001
seed = 1
batch_size = 128
epochs = 10

[nn_config]
# NRDE model parameters
hidden_size = 64
width_size = 64
depth = 2
out_size = 1

# Log-signature configuration
signature_depth = 3
signature_window_size = 16
