[experiment_config]
model_type = "nrde"
dataset_name = "ou_process"
optimizer = "adam"
learning_rate = 0.001
weight_decay = 0.000001
seed = 1
batch_size = 64
epochs = 200

[nrde_config]

# NRDE model parameters
cde_state_dim = 16
vf_hidden_dim = 32
initial_cond_mlp_depth = 2
vf_mlp_depth = 3
out_size = 1

# Log-signature configuration
signature_depth = 2
signature_window_size = 16
